import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

import { TotpEnrollment } from './account.model';
import { AccountService, detailOf } from './account.service';

type Mode = 'off' | 'enrolling' | 'on';
type Prompt = 'none' | 'enroll' | 'disable' | 'regenerate';

const CODE_PATTERN = /^\d{6}$/;

/** Group a base32 seed into readable four-character blocks. */
export function groupSecret(secret: string): string {
  return (secret.match(/.{1,4}/g) ?? []).join(' ');
}

/**
 * Authenticator enrolment, recovery codes, and turning the second factor off.
 *
 * Every secret this panel handles — the TOTP seed, the recovery codes, and the
 * password that guards a change — lives in component state and nowhere else.
 * Leaving the tab destroys the component, which is what makes "shown once"
 * true: there is no store to read them back out of.
 */
@Component({
  selector: 'app-two-factor-tab',
  imports: [],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './two-factor-tab.html',
  styleUrl: './two-factor-tab.scss',
})
export class TwoFactorTab {
  private readonly account = inject(AccountService);

  private readonly enrollment = signal<TotpEnrollment | null>(null);
  private readonly code = signal('');
  private readonly password = signal('');
  private readonly codes = signal<string[]>([]);

  protected readonly busy = signal(false);
  protected readonly error = signal('');
  protected readonly notice = signal('');
  protected readonly prompt = signal<Prompt>('none');
  protected readonly copied = signal(false);

  protected readonly codeValue = this.code.asReadonly();
  protected readonly passwordValue = this.password.asReadonly();
  protected readonly recoveryCodes = this.codes.asReadonly();

  protected readonly mode = computed<Mode>(() => {
    if (this.enrollment() !== null) {
      return 'enrolling';
    }
    return this.account.mfaEnabled() ? 'on' : 'off';
  });

  protected readonly secret = computed(() => groupSecret(this.enrollment()?.secret ?? ''));
  protected readonly otpauthUri = computed(() => this.enrollment()?.otpauth_uri ?? '');

  /**
   * The provisioning QR, rendered by the API with a tested encoder and inlined
   * here. Trusted because it is generated by this application's own backend
   * from a value the backend itself minted, never from user input.
   */
  protected readonly qrCode = computed<SafeHtml | null>(() => {
    const markup = this.enrollment()?.qr_svg;
    return markup ? this.sanitizer.bypassSecurityTrustHtml(markup) : null;
  });

  private readonly sanitizer = inject(DomSanitizer);
  protected readonly issuer = computed(() => this.enrollment()?.issuer ?? '');
  protected readonly codeValid = computed(() => CODE_PATTERN.test(this.code()));
  protected readonly hasCodes = computed(() => this.codes().length > 0);
  protected readonly canCopy = computed(() => typeof navigator?.clipboard?.writeText === 'function');

  // ------------------------------------------------------------- enrolment

  private async startEnrollment(password: string): Promise<void> {
    this.reset();
    this.enrollment.set(await this.account.enrollTotp(password));
  }

  protected cancelEnrollment(): void {
    this.enrollment.set(null);
    this.code.set('');
    this.error.set('');
  }

  protected setCode(event: Event): void {
    this.code.set(valueOf(event).replace(/\D/g, '').slice(0, 6));
    this.error.set('');
  }

  protected async verify(): Promise<void> {
    if (!this.codeValid() || this.busy()) {
      return;
    }
    this.busy.set(true);
    this.error.set('');
    try {
      const codes = await this.account.confirmTotp(this.code());
      // The seed has done its job; only the recovery codes stay on screen.
      this.enrollment.set(null);
      this.code.set('');
      this.codes.set(codes);
      this.notice.set('Two-factor authentication is on.');
    } catch (cause) {
      this.error.set(detailOf(cause));
    } finally {
      this.busy.set(false);
    }
  }

  // -------------------------------------------------------- password prompt

  protected openPrompt(prompt: Prompt): void {
    this.prompt.set(prompt);
    this.password.set('');
    this.error.set('');
    this.notice.set('');
  }

  protected closePrompt(): void {
    this.prompt.set('none');
    this.password.set('');
  }

  protected setPassword(event: Event): void {
    this.password.set(valueOf(event));
    this.error.set('');
  }

  protected async confirmPrompt(): Promise<void> {
    const password = this.password();
    if (!password || this.busy()) {
      return;
    }
    const action = this.prompt();
    this.busy.set(true);
    this.error.set('');
    try {
      if (action === 'enroll') {
        await this.startEnrollment(password);
      } else if (action === 'disable') {
        await this.account.disableTotp(password);
        this.codes.set([]);
        this.notice.set('Two-factor authentication is off.');
      } else if (action === 'regenerate') {
        this.codes.set(await this.account.regenerateRecoveryCodes(password));
        this.notice.set('A new set of recovery codes was issued. The previous set no longer works.');
      }
      this.closePrompt();
    } catch (cause) {
      this.error.set(detailOf(cause));
    } finally {
      // The password is spent either way, so it never outlives the request.
      this.password.set('');
      this.busy.set(false);
    }
  }

  // -------------------------------------------------------- recovery codes

  protected dismissCodes(): void {
    this.codes.set([]);
    this.copied.set(false);
  }

  protected async copyCodes(): Promise<void> {
    if (!this.canCopy() || !this.hasCodes()) {
      return;
    }
    try {
      await navigator.clipboard.writeText(this.codes().join('\n'));
      this.copied.set(true);
    } catch {
      this.error.set('The browser refused access to the clipboard. Select the codes and copy them.');
    }
  }

  protected downloadCodes(): void {
    if (!this.hasCodes()) {
      return;
    }
    const body = `${this.codes().join('\n')}\n`;
    const url = URL.createObjectURL(new Blob([body], { type: 'text/plain' }));
    const link = document.createElement('a');
    link.href = url;
    link.download = 'config-guardian-recovery-codes.txt';
    link.click();
    // The object URL is the only remaining reference to the codes; drop it.
    URL.revokeObjectURL(url);
  }

  private reset(): void {
    this.error.set('');
    this.notice.set('');
    this.codes.set([]);
    this.code.set('');
    this.prompt.set('none');
    this.password.set('');
  }
}

function valueOf(event: Event): string {
  return (event.target as HTMLInputElement).value;
}
