export const now = '2026-09-09T12:00:00Z';
export const user = {
  id: 'test-user',
  email: 'admin@example.test',
  display_name: 'Test Administrator',
  role: 'administrator',
  is_active: true,
  status: 'active',
  preferences: { timezone: 'UTC', clock: '24h', landing_page: 'overview' },
  mfa_enabled: true,
  passkey_count: 0,
};
export const org = {
  id: 'org1',
  name: 'TM-LAB',
  mist_org_id: 'mist1',
  cloud_region: 'global_02',
  status: 'verified',
  service_token_set: true,
  service_token_last_four: 'test',
  credential_verified_at: now,
  credential_error: null,
  discovered_privileges: ['read'],
  webhook_secret_set: true,
  webhook_secret_last_four: 'test',
  webhook_secret_rotated_at: now,
  webhook_last_received_at: now,
  webhook_last_signature_valid: true,
  initial_snapshot_completed_at: now,
  reconciliation_cron: '0 2 * * *',
  configuration_retention_days: 365,
  monitoring_retention_days: 90,
  created_at: now,
  updated_at: now,
};
export const objects = Array.from({ length: 100 }, (_, i) => ({
  id: 'o' + i,
  scope: 'site',
  object_type: 'settings',
  name: 'Lab site ' + i,
  current_mist_id: 'site' + i,
  site_mist_id: 'site1',
  is_deleted: false,
  current_version: 2,
  updated_at: now,
}));
export const groups = Array.from({ length: 70 }, (_, i) => ({
  id: 'g' + i,
  audit_id: 'audit' + i,
  actor: 'Admin',
  source: 'webhook',
  occurred_at: now,
  title: 'Template deployment ' + i,
  summary: 'Network template updated',
  object_count: 1,
  device_count: 6,
  affected_site_ids: ['site1'],
  devices_label: '6 switches',
  impact_severity: 'none',
  recovery_state: 'completed',
  impact_label: 'NO IMPACT',
  degraded_metrics: [],
  metrics: [],
  monitoring_session_ids: [],
  is_mine: false,
}));
export const observation = {
  captured_at: now,
  device: { status: 'connected' },
  radios: [],
  wlans: [],
  clients: [],
  ports: [{ port_id: 'ge-0/0/1', up: true, poe_on: true }],
  bgp: [],
  ospf: [],
  tunnels: [],
  vpn_peers: [],
  available: ['device', 'ports'],
  errors: {},
};
export const sessions = Array.from({ length: 6 }, (_, i) => ({
  id: 's' + i,
  audit_ids: ['audit0'],
  change_groups: [
    { id: 'g0', audit_id: 'audit0', title: 'Template deployment 0', occurred_at: now },
  ],
  site_id: 'site1',
  device_mac: 'aabbccddee0' + i,
  device_name: 'Switch ' + i,
  device_type: 'switch',
  status: 'monitoring',
  baseline: { captured_at: now, values: { 'switch-throughput': 99 }, errors: [] },
  observations: [{ captured_at: now, values: { 'switch-throughput': 99 }, errors: [] }],
  incidents: [],
  config_applied_at: now,
  monitoring_started_at: now,
  monitoring_ends_at: '2026-09-09T13:00:00Z',
  impact_severity: 'none',
  peak_impact_severity: 'critical',
  deterministic_summary: 'No negative impact detected.',
  degraded_metrics: [],
  warnings: [],
  created_at: now,
  completed_at: null,
  device_comparisons: [
    {
      triggered_at: now,
      due_at: now,
      baseline: observation,
      followup: observation,
      latest: observation,
      current_findings: [],
      findings: [],
      recovered_at: now,
    },
  ],
  device_findings: [],
  timeline: [
    { key: 'e1', event_type: 'SW_CONFIG_CHANGED_BY_USER', occurred_at: now, received_at: now },
  ],
}));
