apiVersion: v1
kind: Service
metadata:
  name: {{ include "mist-config-guardian.fullname" . }}-api
  labels:
    {{- include "mist-config-guardian.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "mist-config-guardian.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
