apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mist-config-guardian.fullname" . }}-worker
  labels:
    {{- include "mist-config-guardian.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.workerReplicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mist-config-guardian.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "mist-config-guardian.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - mist_config_guardian_backend.worker.celery_app
            - worker
            - --loglevel=INFO
          envFrom:
            - configMapRef:
                name: {{ include "mist-config-guardian.fullname" . }}
            - secretRef:
                name: {{ include "mist-config-guardian.secretName" . }}
          env:
            {{- include "mist-config-guardian.datastoreEnv" . | trim | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: temp
              mountPath: /tmp
          resources:
            {{- toYaml .Values.workerResources | nindent 12 }}
      volumes:
        - name: temp
          emptyDir: {}
